name: parse_server
description: Parse Server Dart SDK.
version: 0.0.4
homepage: https://www.github.com/lotux
author: lotux <basirat@gmail.com>

environment:
  sdk: '>=2.0.0 <2.2.0'

dependencies:
  path:
  web_socket_channel:
  http:

